In [1]:
import pandas as pd

# واحد صورت‌های مالی: میلیون ریال
# مبنای مقایسه: ۱۴۰۳ تجدیدارائه‌شده در گزارش ۱۴۰۴
data = {
    "سال": [1403, 1404],
    "درآمد عملیاتی": [1_789_892_699, 3_218_894_510],
    "بهای تمام‌شده": [806_422_709, 1_354_424_181],
    "سود ناخالص": [983_469_990, 1_864_470_329],
    "سود خالص": [779_773_874, 1_460_550_037],
    "دارایی جاری": [1_258_762_744, 2_222_444_657],
    "کل دارایی‌ها": [2_879_151_852, 4_985_804_911],
    "بدهی جاری": [878_842_280, 1_841_806_377],
    "کل بدهی‌ها": [934_764_626, 1_914_

SyntaxError: invalid decimal literal (3965541815.py, line 14)

In [2]:
import pandas as pd

# واحد صورت‌های مالی: میلیون ریال
# مبنای مقایسه: ۱۴۰۳ تجدیدارائه‌شده در گزارش ۱۴۰۴
data = {
    "سال": [1403, 1404],
    "درآمد عملیاتی": [1_789_892_699, 3_218_894_510],
    "بهای تمام‌شده": [806_422_709, 1_354_424_181],
    "سود ناخالص": [983_469_990, 1_864_470_329],
    "سود خالص": [779_773_874, 1_460_550_037],
    "دارایی جاری": [1_258_762_744, 2_222_444_657],
    "کل دارایی‌ها": [2_879_151_852, 4_985_804_911],
    "بدهی جاری": [878_842_280, 1_841_806_377],
    "کل بدهی‌ها": [934_764_626, 1_914_606_935],
    "حقوق مالکانه": [1_944_387_226, 3_071_197_976],
    "موجودی کالا": [311_731_608, 694_556_486],
    "دریافتنی تجاری و سایر": [603_228_877, 901_580_580],
    "وجه نقد": [64_075_948, 161_608_044],
    "جریان نقد عملیاتی": [819_677_371, 1_620_265_320],
}

df = pd.DataFrame(data).set_index("سال")
df

,درآمد عملیاتی,بهای تمام‌شده,سود ناخالص,سود خالص,دارایی جاری,کل دارایی‌ها,بدهی جاری,کل بدهی‌ها,حقوق مالکانه,موجودی کالا,دریافتنی تجاری و سایر,وجه نقد,جریان نقد عملیاتی
سال,,,,,,,,,,,,,
1403,1789892699,806422709,983469990,779773874,1258762744,2879151852,878842280,934764626,1944387226,311731608,603228877,64075948,819677371
1404,3218894510,1354424181,1864470329,1460550037,2222444657,4985804911,1841806377,1914606935,3071197976,694556486,901580580,161608044,1620265320

In [3]:
# بررسی اینکه سود ناخالص با درآمد منهای بهای تمام‌شده برابر باشد
df["کنترل سود ناخالص"] = (
    df["درآمد عملیاتی"] - df["بهای تمام‌شده"] - df["سود ناخالص"]
)

df[["درآمد عملیاتی", "بهای تمام‌شده", "سود ناخالص", "کنترل سود ناخالص"]]

      درآمد عملیاتی  بهای تمام‌شده  سود ناخالص  کنترل سود ناخالص
سال
1403     1789892699      806422709   983469990                 0
1404     3218894510     1354424181  1864470329                 0

In [4]:
# رشد ۱۴۰۴ نسبت به ۱۴۰۳
growth = (
    df.loc[1404] / df.loc[1403] - 1
) * 100

# حاشیه‌های سود
margins = pd.DataFrame(index=df.index)
margins["حاشیه سود ناخالص (%)"] = (
    df["سود ناخالص"] / df["درآمد عملیاتی"] * 100
)
margins["حاشیه سود خالص (%)"] = (
    df["سود خالص"] / df["درآمد عملیاتی"] * 100
)

print("رشد ۱۴۰۴ نسبت به ۱۴۰۳:")
display(growth.to_frame("رشد (%)").round(2))

print("حاشیه‌های سود:")
display(margins.round(2))

رشد ۱۴۰۴ نسبت به ۱۴۰۳:

                       رشد (%)
درآمد عملیاتی            79.84
بهای تمام‌شده            67.95
سود ناخالص               89.58
سود خالص                 87.30
دارایی جاری              76.56
کل دارایی‌ها             73.17
بدهی جاری               109.57
کل بدهی‌ها              104.82
حقوق مالکانه             57.95
موجودی کالا             122.81
دریافتنی تجاری و سایر    49.46
وجه نقد                 152.21
جریان نقد عملیاتی        97.67
کنترل سود ناخالص           NaN

حاشیه‌های سود:

      حاشیه سود ناخالص (%)  حاشیه سود خالص (%)
سال
1403                 54.95               43.57
1404                 57.92               45.37

In [5]:
liquidity = pd.DataFrame(index=df.index)

# سرمایه در گردش = دارایی جاری - بدهی جاری
liquidity["سرمایه در گردش (میلیون ریال)"] = (
    df["دارایی جاری"] - df["بدهی جاری"]
)

# نسبت جاری = دارایی جاری / بدهی جاری
liquidity["نسبت جاری"] = (
    df["دارایی جاری"] / df["بدهی جاری"]
)

# نسبت آنی = (دارایی جاری - موجودی کالا) / بدهی جاری
liquidity["نسبت آنی"] = (
    (df["دارایی جاری"] - df["موجودی کالا"]) / df["بدهی جاری"]
)

# نسبت نقدی = وجه نقد / بدهی جاری
liquidity["نسبت نقدی"] = (
    df["وجه نقد"] / df["بدهی جاری"]
)

display(liquidity.round(2))

      سرمایه در گردش (میلیون ریال)  نسبت جاری  نسبت آنی  نسبت نقدی
سال
1403                     379920464       1.43      1.08       0.07
1404                     380638280       1.21      0.83       0.09

In [6]:
leverage = pd.DataFrame(index=df.index)

# نسبت بدهی = کل بدهی‌ها / کل دارایی‌ها
leverage["نسبت بدهی (%)"] = (
    df["کل بدهی‌ها"] / df["کل دارایی‌ها"] * 100
)

# نسبت حقوق مالکانه به دارایی‌ها
leverage["حقوق مالکانه به دارایی‌ها (%)"] = (
    df["حقوق مالکانه"] / df["کل دارایی‌ها"] * 100
)

# نسبت بدهی به حقوق مالکانه
leverage["بدهی به حقوق مالکانه"] = (
    df["کل بدهی‌ها"] / df["حقوق مالکانه"]
)

display(leverage.round(2))

      نسبت بدهی (%)  حقوق مالکانه به دارایی‌ها (%)  بدهی به حقوق مالکانه
سال
1403          32.47                          67.53                  0.48
1404          38.40                          61.60                  0.62

In [7]:
# مانده‌های میانگین ۱۴۰۴
avg_assets_1404 = (
    df.loc[1403, "کل دارایی‌ها"] + df.loc[1404, "کل دارایی‌ها"]
) / 2

avg_inventory_1404 = (
    df.loc[1403, "موجودی کالا"] + df.loc[1404, "موجودی کالا"]
) / 2

avg_receivables_1404 = (
    df.loc[1403, "دریافتنی تجاری و سایر"]
    + df.loc[1404, "دریافتنی تجاری و سایر"]
) / 2

# گردش دارایی‌ها
asset_turnover_1404 = (
    df.loc[1404, "درآمد عملیاتی"] / avg_assets_1404
)

# گردش موجودی کالا و روزهای نگهداری موجودی (DIO)
inventory_turnover_1404 = (
    df.loc[1404, "بهای تمام‌شده"] / avg_inventory_1404
)
dio_1404 = 365 / inventory_turnover_1404

# گردش دریافتنی‌ها و روزهای وصول مطالبات (DSO)
receivables_turnover_1404 = (
    df.loc[1404, "درآمد عملیاتی"] / avg_receivables_1404
)
dso_1404 = 365 / receivables_turnover_1404

efficiency_1404 = pd.Series({
    "میانگین کل دارایی‌ها (میلیون ریال)": avg_assets_1404,
    "گردش دارایی": asset_turnover_1404,
    "گردش موجودی کالا": inventory_turnover_1404,
    "DIO (روز)": dio_1404,
    "گردش دریافتنی‌ها": receivables_turnover_1404,
    "DSO (روز)": dso_1404,
})

display(efficiency_1404.to_frame("۱۴۰۴").round(2))

                                            ۱۴۰۴
میانگین کل دارایی‌ها (میلیون ریال)  3.932478e+09
گردش دارایی                         8.200000e-01
گردش موجودی کالا                    2.690000e+00
DIO (روز)                           1.355900e+02
گردش دریافتنی‌ها                    4.280000e+00
DSO (روز)                           8.532000e+01

In [8]:
cash_quality = pd.DataFrame(index=df.index)

cash_quality["جریان نقد عملیاتی به سود خالص"] = (
    df["جریان نقد عملیاتی"] / df["سود خالص"]
)

display(cash_quality.round(2))

      جریان نقد عملیاتی به سود خالص
سال
1403                           1.05
1404                           1.11

In [9]:
# مقادیر را با ارقام گزارش، به میلیون ریال، جایگزین کن
capex = pd.Series({
    1403: 0,
    1404: 0,
})

cash_quality["مخارج سرمایه‌ای (میلیون ریال)"] = capex
cash_quality["جریان نقد آزاد (میلیون ریال)"] = (
    df["جریان نقد عملیاتی"] - capex
)
cash_quality["پوشش مخارج سرمایه‌ای"] = (
    df["جریان نقد عملیاتی"] / capex
)

display(cash_quality.round(2))

,جریان نقد عملیاتی به سود خالص,مخارج سرمایه‌ای (میلیون ریال),جریان نقد آزاد (میلیون ریال),پوشش مخارج سرمایه‌ای
سال,,,,
1403,1.05,0,819677371,inf
1404,1.11,0,1620265320,inf

In [10]:
# ارقام تلفیقی گزارش ۱۴۰۴؛ واحد: میلیون ریال
df.loc[1403, "جریان نقد عملیاتی"] = 785_588_772
df.loc[1404, "جریان نقد عملیاتی"] = 1_601_404_689

# CapEx = خرید دارایی‌های ثابت مشهود + نامشهود
capex = pd.Series({
    1403: 546_370_024 + 931_506,
    1404: 1_124_972_442 + 142_043,
})

cash_quality = pd.DataFrame(index=df.index)
cash_quality["جریان نقد عملیاتی / سود خالص"] = (
    df["جریان نقد عملیاتی"] / df["سود خالص"]
)
cash_quality["مخارج سرمایه‌ای (میلیون ریال)"] = capex
cash_quality["جریان نقد آزاد (میلیون ریال)"] = (
    df["جریان نقد عملیاتی"] - capex
)
cash_quality["پوشش مخارج سرمایه‌ای"] = (
    df["جریان نقد عملیاتی"] / capex
)

display(cash_quality.round(2))

,جریان نقد عملیاتی / سود خالص,مخارج سرمایه‌ای (میلیون ریال),جریان نقد آزاد (میلیون ریال),پوشش مخارج سرمایه‌ای
سال,,,,
1403,1.01,547301530,238287242,1.44
1404,1.10,1125114485,476290204,1.42

In [11]:
# محاسبه ROA و ROE برای سال ۱۴۰۴ بر پایه میانگین دارایی‌ها و حقوق مالکانه
avg_assets_1404 = (df.loc[1403, "کل دارایی‌ها"] + df.loc[1404, "کل دارایی‌ها"]) / 2
avg_equity_1404 = (df.loc[1403, "حقوق مالکانه"] + df.loc[1404, "حقوق مالکانه"]) / 2

profitability = pd.DataFrame(index=[1404])
profitability["میانگین کل دارایی‌ها"] = avg_assets_1404
profitability["میانگین حقوق مالکانه"] = avg_equity_1404
profitability["ROA (بازده دارایی‌ها)"] = (df.loc[1404, "سود خالص"] / avg_assets_1404) * 100
profitability["ROE (بازده حقوق مالکانه)"] = (df.loc[1404, "سود خالص"] / avg_equity_1404) * 100

display(profitability.round(2))

,میانگین کل دارایی‌ها,میانگین حقوق مالکانه,ROA (بازده دارایی‌ها),ROE (بازده حقوق مالکانه)
1404,3.932478e+09,2.507793e+09,37.14,58.24

In [12]:
# ارقام سود عملیاتی و هزینه مالی از صورت سود و زیان تلفیقی (میلیون ریال)
# سال ۱۴۰۳ تجدیدارائه‌شده و ۱۴۰۴ بر اساس گزارش تلفیقی ۱۴۰۴
ebit = pd.Series({
    1403: 948_665_448,
    1404: 1_826_976_769
})

interest_expense = pd.Series({
    1403: 4_797_528,
    1404: 10_397_405
})

debt_service = pd.DataFrame(index=df.index)
debt_service["سود عملیاتی (EBIT)"] = ebit
debt_service["هزینه‌های مالی"] = interest_expense
debt_service["پوشش بهره (مرتبه)"] = ebit / interest_expense
debt_service["نسبت هزینه مالی به درآمد (٪)"] = (interest_expense / df["درآمد عملیاتی"]) * 100

display(debt_service.round(2))

,سود عملیاتی (EBIT),هزینه‌های مالی,پوشش بهره (مرتبه),نسبت هزینه مالی به درآمد (٪)
سال,,,,
1403,948665448,4797528,197.74,0.27
1404,1826976769,10397405,175.71,0.32

In [13]:
# تجمیع شاخص‌های کلیدی عملکرد (KPI) در یک جدول جامع
kpi_summary = pd.DataFrame(index=[1403, 1404])

# ۱. حاشیه‌های سودآوری
kpi_summary["حاشیه ناخالص (٪)"] = (df["سود ناخالص"] / df["درآمد عملیاتی"]) * 100
kpi_summary["حاشیه خالص (٪)"] = (df["سود خالص"] / df["درآمد عملیاتی"]) * 100

# ۲. نقدینگی
kpi_summary["نسبت جاری"] = df["دارایی جاری"] / df["بدهی جاری"]
kpi_summary["نسبت آنی"] = (df["دارایی جاری"] - df["موجودی"]) / df["بدهی جاری"]

# ۳. اهرم مالی
kpi_summary["بدهی به دارایی (٪)"] = (df["کل بدهی‌ها"] / df["کل دارایی‌ها"]) * 100
kpi_summary["بدهی به حقوق مالکانه"] = df["کل بدهی‌ها"] / df["حقوق مالکانه"]

# ۴. پوشش و کیفیت جریان نقد
kpi_summary["CFO / سود خالص"] = cash_quality["جریان نقد عملیاتی / سود خالص"]
kpi_summary["پوشش CapEx"] = cash_quality["پوشش مخارج سرمایه‌ای"]
kpi_summary["پوشش بهره"] = debt_service["پوشش بهره (مرتبه)"]

# نمایش با دو رقم اعشار
display(kpi_summary.T.round(2))

KeyError: 'موجودی'

In [14]:
# ۱. اضافه کردن ستون موجودی (اگر وجود ندارد)
# ارقام: ۱۴۰۳ -> 311,731,608 | ۱۴۰۴ -> 694,556,486
df["موجودی"] = [311_731_608, 694_556_486]

# ۲. اجرای مجدد کد تجمیع (KPI Summary)
kpi_summary = pd.DataFrame(index=[1403, 1404])

# حاشیه‌ها
kpi_summary["حاشیه ناخالص (٪)"] = (df["سود ناخالص"] / df["درآمد عملیاتی"]) * 100
kpi_summary["حاشیه خالص (٪)"] = (df["سود خالص"] / df["درآمد عملیاتی"]) * 100

# نقدینگی
kpi_summary["نسبت جاری"] = df["دارایی جاری"] / df["بدهی جاری"]
kpi_summary["نسبت آنی"] = (df["دارایی جاری"] - df["موجودی"]) / df["بدهی جاری"]

# اهرم مالی
kpi_summary["بدهی به دارایی (٪)"] = (df["کل بدهی‌ها"] / df["کل دارایی‌ها"]) * 100
kpi_summary["بدهی به حقوق مالکانه"] = df["کل بدهی‌ها"] / df["حقوق مالکانه"]

# پوشش و کیفیت
kpi_summary["CFO / سود خالص"] = cash_quality["جریان نقد عملیاتی / سود خالص"]
kpi_summary["پوشش CapEx"] = cash_quality["پوشش مخارج سرمایه‌ای"]
kpi_summary["پوشش بهره"] = debt_service["پوشش بهره (مرتبه)"]

# نمایش نهایی
display(kpi_summary.T.round(2))

                        1403    1404
حاشیه ناخالص (٪)       54.95   57.92
حاشیه خالص (٪)         43.57   45.37
نسبت جاری               1.43    1.21
نسبت آنی                1.08    0.83
بدهی به دارایی (٪)     32.47   38.40
بدهی به حقوق مالکانه    0.48    0.62
CFO / سود خالص          1.01    1.10
پوشش CapEx              1.44    1.42
پوشش بهره             197.74  175.71

In [15]:
# داده‌های بودجه اعلامی مدیریت برای سال ۱۴۰۵ (میلیون ریال)
mgmt_sales_1405 = 5_187_497_535
mgmt_cogs_1405 = 2_460_192_922
mgmt_gross_profit_1405 = 2_727_304_613

# تعریف سناریوهای پیش‌بینی ۱۴۰۵
scenarios = {
    "سناریوی محافظه‌کارانه (Bear)": {
        "درآمد عملیاتی": mgmt_sales_1405 * 0.90,
        "حاشیه خالص": 0.38
    },
    "سناریوی پایه (مدیریت - Base)": {
        "درآمد عملیاتی": mgmt_sales_1405,
        "حاشیه خالص": 0.42
    },
    "سناریوی خوش‌بینانه (Bull)": {
        "درآمد عملیاتی": mgmt_sales_1405 * 1.10,
        "حاشیه خالص": 0.45
    }
}

# ساخت دیتافریم پیش‌بینی
forecast_1405 = pd.DataFrame(scenarios).T
forecast_1405["سود خالص برآوردی (میلیون ریال)"] = forecast_1405["درآمد عملیاتی"] * forecast_1405["حاشیه خالص"]
forecast_1405["رشد سود خالص نسبت به ۱۴۰۴ (٪)"] = (
    (forecast_1405["سود خالص برآوردی (میلیون ریال)"] - df.loc[1404, "سود خالص"]) / df.loc[1404, "سود خالص"]
) * 100

forecast_1405["حاشیه خالص (٪)"] = forecast_1405["حاشیه خالص"] * 100

# مرتب‌سازی ستون‌ها و نمایش
cols = ["درآمد عملیاتی", "حاشیه خالص (٪)", "سود خالص برآوردی (میلیون ریال)", "رشد سود خالص نسبت به ۱۴۰۴ (٪)"]
display(forecast_1405[cols].round(2))

,درآمد عملیاتی,حاشیه خالص (٪),سود خالص برآوردی (میلیون ریال),رشد سود خالص نسبت به ۱۴۰۴ (٪)
سناریوی محافظه‌کارانه (Bear),4.668748e+09,38.0,1.774124e+09,21.47
سناریوی پایه (مدیریت - Base),5.187498e+09,42.0,2.178749e+09,49.17
سناریوی خوش‌بینانه (Bull),5.706247e+09,45.0,2.567811e+09,75.81